version: "3.9"
services:
  whatsapp-connector:
    build:
      context: ./whatsapp-connector/
    command: npm run start
    environment:
      - VERIFY_TOKEN=%VERIFY_TOKEN%
      - WHATSAPP_TOKEN=%WHATSAPP_TOKEN%
      - WHATSAPP_SEND_MESSAGE_API=%WHATSAPP_SEND_MESSAGE_API%
      - CHATBOT_URL=%CHATBOT_URL%
      - PORT=8081
  chatbot:
    build:
      context: ./chatbot/
    command: npm run start
    environment:
      - OPENAI_API_KEY=%OPENAI_API_KEY%
      - PORT=8080
  nginx:
    image: nginx:latest
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
