version: "3.9"
services:
  whatsapp-connector:
    build:
      context: ../whatsapp-connector
    command: npm run start
    environment:
      - VERIFY_TOKEN=%VERIFY_TOKEN%
      - WHATSAPP_TOKEN=%WHATSAPP_TOKEN%
      - WHATSAPP_SEND_MESSAGE_API=%WHATSAPP_SEND_MESSAGE_API%
      - CHATBOT_URL=%CHATBOT_URL%
      - PORT=8081
    ports:
      - 8081:8081
  chatbot:
    build:
      context: ../chatbot
    command: npm run start
    environment:
      - OPENAI_API_KEY=%OPENAI_API_KEY%
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
