name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:latest ./chatbot/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:latest ./whatsapp-connector/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:latest
  artifacts:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Compose Edit
        run: |
          sed -i "s+%VERIFY_TOKEN%+${{ secrets.VERIFY_TOKEN }}+g" docker/docker-compose.yml
          sed -i "s+%WHATSAPP_TOKEN%+${{ secrets.WHATSAPP_TOKEN }}+g" docker/docker-compose.yml
          sed -i "s+%WHATSAPP_SEND_MESSAGE_API%+${{ secrets.WHATSAPP_SEND_MESSAGE_API }}+g" docker/docker-compose.yml
          sed -i "s+%CHATBOT_URL%+${{ secrets.CHATBOT_URL }}+g" docker/docker-compose.yml
          sed -i "s+%OPENAI_API_KEY%+${{ secrets.OPENAI_API_KEY }}+g" docker/docker-compose.yml
      - name: Copy Docker Compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_SERVER_HOST }}
          username: ${{ secrets.LINODE_SERVER_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          source: "docker/docker-compose.yml"
          target: "~"
          overwrite: true
      - name: Copy Nginx Conf
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_SERVER_HOST }}
          username: ${{ secrets.LINODE_SERVER_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          source: "nginx/nginx.conf"
          target: "~/docker"
          overwrite: true
  deploy:
    needs: [build, artifacts]
    runs-on: ubuntu-latest
    steps:
      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_SERVER_HOST }}
          username: ${{ secrets.LINODE_SERVER_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            docker-compose -f docker/docker-compose.yml up -d --build --force-recreate --remove-orphans
