name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build and Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:latest ./chatbot/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:latest ./whatsapp-connector/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CHATBOT_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_WHATSAPP_CONNECTOR_REPOSITORY }}:latest
  artifacts:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Copy Nginx Conf
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_SERVER_HOST }}
          username: ${{ secrets.LINODE_SERVER_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          source: "nginx/nginx.conf"
          target: "nginx"
          overwrite: true
  deploy:
    needs: [build, artifacts]
    runs-on: ubuntu-latest
    steps:
      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_SERVER_HOST }}
          username: ${{ secrets.LINODE_SERVER_USERNAME }}
          key: ${{ secrets.LINODE_SSH_KEY }}
          script: |
            docker-compose up -d --build --force-recreate
